### ISSUE TITLE
web端的docker拉不下来？

### ISSUE THREAD

**Issue by CZYAce** [lmjben/cdfang-spider#36]
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

**Comment by lmjben** [comment]
> ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

@CZYAce 之前更改了名字，现已修复，感谢指出。
