### ISSUE TITLE
寻求商务合作

### ISSUE THREAD

**Issue by specialzxw** [lmjben/cdfang-spider#38]
您好，我们对您分享的“成都房源”项目十分感兴趣，想与您建立商务合作，可是您在github上没有留下联系方式，您方便留一下您邮箱或微信吗？方便我们与您取得联系~

**Comment by lmjben** [comment]
> 您好，我们对您分享的“成都房源”项目十分感兴趣，想与您建立商务合作，可是您在github上没有留下联系方式，您方便留一下您邮箱或微信吗？方便我们与您取得联系~
微信：yhl2016226
